name: 'Deploy webapp'
on:
  - push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS2 }}
      - uses: Azure/get-keyvault-secrets@v1.0
        with:
          keyvault: 'kv-falkeredet-core'
          secrets: 'acrSpClientId, acrSpClientSecret'
        id: getSecretAction
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Build WebApp'
        run: mvn -U clean package
      - uses: docker/build-push-action@v1
        with:
          username: ${{ steps.getSecretAction.outputs.acrSpClientId }}
          password: ${{ steps.getSecretAction.outputs.acrSpClientSecret }}
          registry: falkeregistry.azurecr.io
          repository: falkeazure
          tag_with_ref: true
          tag_with_sha: true
